### ISSUE TITLE
List of test results in Test Explorer should show test duration

### ISSUE THREAD

**Issue by bkuhns** [SeanCline/CatchVsTestAdapter#4]
Tests from the MS Test framework will show the duration (in milliseconds) of each test in the test list. This Catch test runner should do the same. If duration is less than 1 millisecond, it should be displayed as "< 1ms". 

Screenshot example:

![2014-10-10 11_10_31-c64devbret - remote desktop connection](https://cloud.githubusercontent.com/assets/222991/4594432/a0d31ccc-508f-11e4-99f9-9c7791707a55.png)

**Comment by SeanCline** [comment]
It looks like this issue was left open after 7ef55dbb6585ad7feae43231b33243a857130ef4 resolved it. Closing it now.
